package app;
//======================================================
// Source code generated by jvider v1.8.1 UNREGISTERED version.
// http://www.jvider.com/
//======================================================

import controller.DataManager;
import org.aeonbits.owner.ConfigFactory;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import view.MainPanel;

import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Locale;
import java.util.ResourceBundle;

public class TodoHelper extends JFrame {

    private static  AppConfig config = ConfigFactory.create(AppConfig.class);
    private static ResourceBundle text = ResourceBundle
            .getBundle("lang", new Locale(config.language(), config.country()));
    private Logger logger = LoggerFactory.getLogger(TodoHelper.class);
    private static JFrame app;

    public static void main(String[] args) {
        EventQueue.invokeLater(() -> {
            app = new TodoHelper();
            app.setVisible(true);
        });
    }

    private TodoHelper() {
        showLogInMonit();
        initGUI();
    }

    private void initGUI() {
        logger.info("Initializing JFrame window");
        add(MainPanel.getMainPanel());
        logger.debug("Adding JPanel to Frame");
        Boolean resizable = false;
        setResizable(resizable);
        logger.debug("Resizable parameter set to {}", resizable);
        setFocusable(true);
        pack();
        setTitle("TODO Helper");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    public static void shutDownTheApp() {
        app.setVisible(false);
        restartPrompt();
        app.dispose();
    }

    private static void restartPrompt() {
        JOptionPane.showMessageDialog(app, text.getString("restartMonit"));
    }

    private static boolean showLogInMonit() {
        JTextField loginField = new JTextField();
        JTextField passField = new JTextField();
        Object[] fields = {
                "login: ",
                loginField,
                "password: ",
                passField
        };

        int result = JOptionPane.showConfirmDialog(app, fields, text.getString("editButton"), JOptionPane.OK_CANCEL_OPTION);
        if(result == JOptionPane.OK_OPTION) {
            if(loginField.getText() != null && !loginField.getText().equals("") &&
                    passField.getText() != null && !passField.getText().equals("")) {
                boolean res = DataManager.getManager().getAuthController().logIn("gregory531", "1234");
                System.out.println("res:"+res);
            }
        }
        return false;
    }

}
