
//======================================================
// Source code generated by jvider v1.8.1 UNREGISTERED version.
// http://www.jvider.com/
//======================================================

import javax.swing.JFrame;
import java.awt.*;

public class TodoHelper extends JFrame {

    public static void main(String[] args) {
        EventQueue.invokeLater(() -> {
            JFrame frame = new TodoHelper();
            frame.setVisible(true);
        });
    }

    private TodoHelper() {
        initGUI();
    }

    private void initGUI() {
        add(MainPanel.getMainPanel());
        setResizable(false);
        pack();
        setTitle("TODO Helper");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

}
