
//======================================================
// Source code generated by jvider v1.8.1 UNREGISTERED version.
// http://www.jvider.com/
//======================================================

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.swing.JFrame;
import java.awt.*;

public class TodoHelper extends JFrame {

    private Logger logger = LoggerFactory.getLogger(TodoHelper.class);

    public static void main(String[] args) {
        EventQueue.invokeLater(() -> {
            JFrame frame = new TodoHelper();
            frame.setVisible(true);
        });
    }

    private TodoHelper() {
        initGUI();
    }

    private void initGUI() {
        logger.info("Initializing JFrame window");
        add(MainPanel.getMainPanel());
        logger.debug("Adding JPanel to Frame");
        Boolean resizable = false;
        setResizable(resizable);
        logger.debug("Resizable parameter set to {}", resizable);
        setFocusable(true);
        pack();
        setTitle("TODO Helper");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

}
